package eu.geosmartcity.hub.pojo;

// default package
// Generated 29-feb-2016 12.40.06 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.vividsolutions.jts.geom.Geometry;

/**
 * Building generated by hbm2java
 */
@Entity
@Table(name = "building", schema = "wps_solar")
public class Building implements java.io.Serializable {
	
	private int id;
	private Double heightValue;
	private Double elevationValue;
	//	private String originalEpsg;
	private Long lifespanBeginning;
	private Long lifespanEnd;
	private Integer idLoad;
	private String identifierInspire;
	private Geometry theGeom;
	
	public Building() {
	}
	
	public Building(int id) {
		this.id = id;
	}
	
	public Building(int id, Double heightValue, Double elevationValue, String originalEpsg, Long lifespanBeginning,
			Long lifespanEnd, Integer idLoad, String identifierInspire, Geometry theGeom) {
		this.id = id;
		this.heightValue = heightValue;
		this.elevationValue = elevationValue;
		//		this.originalEpsg = originalEpsg;
		this.lifespanBeginning = lifespanBeginning;
		this.lifespanEnd = lifespanEnd;
		this.idLoad = idLoad;
		this.identifierInspire = identifierInspire;
		this.theGeom = theGeom;
	}
	
	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "devices_seq_gen")
	@SequenceGenerator(name = "devices_seq_gen", sequenceName = "building_seq", allocationSize = 1)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}
	
	public void setId(int id) {
		this.id = id;
	}
	
	@Column(name = "height_value")
	public Double getHeightValue() {
		return this.heightValue;
	}
	
	public void setHeightValue(Double heightValue) {
		this.heightValue = heightValue;
	}
	
	@Column(name = "elevation_value")
	public Double getElevationValue() {
		return this.elevationValue;
	}
	
	public void setElevationValue(Double elevationValue) {
		this.elevationValue = elevationValue;
	}
	
	//	@Column(name = "original_epsg")
	//	public String getOriginalEpsg() {
	//		return this.originalEpsg;
	//	}
	//	
	//	public void setOriginalEpsg(String originalEpsg) {
	//		this.originalEpsg = originalEpsg;
	//	}
	
	@Column(name = "lifespan_beginning")
	public Long getLifespanBeginning() {
		return this.lifespanBeginning;
	}
	
	public void setLifespanBeginning(Long lifespanBeginning) {
		this.lifespanBeginning = lifespanBeginning;
	}
	
	@Column(name = "lifespan_end")
	public Long getLifespanEnd() {
		return this.lifespanEnd;
	}
	
	public void setLifespanEnd(Long lifespanEnd) {
		this.lifespanEnd = lifespanEnd;
	}
	
	@Column(name = "id_load")
	public Integer getIdLoad() {
		return this.idLoad;
	}
	
	public void setIdLoad(Integer idLoad) {
		this.idLoad = idLoad;
	}
	
	@Column(name = "identifier_inspire")
	public String getIdentifierInspire() {
		return this.identifierInspire;
	}
	
	public void setIdentifierInspire(String identifierInspire) {
		this.identifierInspire = identifierInspire;
	}
	
	@Column(name = "the_geom")
	public Geometry getTheGeom() {
		return this.theGeom;
	}
	
	public void setTheGeom(Geometry theGeom) {
		this.theGeom = theGeom;
	}
	
}
