package it.sinergis.gsc.model;

// Generated Aug 5, 2016 5:19:16 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BuildingsUseMT generated by hbm2java
 */
@Entity
@Table(name = "BUILDINGS_USE_M_T")
public class BuildingsUseMT implements java.io.Serializable {
	
	private Buildings buildings;
	private HCurrentuse HCurrentuse;
	private BuildingsUseMTId id;
	
	public BuildingsUseMT() {
	}
	
	public BuildingsUseMT(BuildingsUseMTId id, HCurrentuse HCurrentuse, Buildings buildings) {
		this.id = id;
		this.HCurrentuse = HCurrentuse;
		this.buildings = buildings;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UUID", nullable = false, insertable = false, updatable = false)
	public Buildings getBuildings() {
		return this.buildings;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USE_M_CURRENTUSE", nullable = false, insertable = false, updatable = false)
	public HCurrentuse getHCurrentuse() {
		return this.HCurrentuse;
	}
	
	@EmbeddedId
	@AttributeOverrides({
	        @AttributeOverride(name = "uuid", column = @Column(name = "UUID", nullable = false, length = 70)),
	        @AttributeOverride(name = "useMCurrentuse", column = @Column(name = "USE_M_CURRENTUSE", nullable = false, length = 80)),
	        @AttributeOverride(name = "useMPercentage", column = @Column(name = "USE_M_PERCENTAGE", nullable = false, precision = 15, scale = 0)) })
	public BuildingsUseMTId getId() {
		return this.id;
	}
	
	public void setBuildings(Buildings buildings) {
		this.buildings = buildings;
	}
	
	public void setHCurrentuse(HCurrentuse HCurrentuse) {
		this.HCurrentuse = HCurrentuse;
	}
	
	public void setId(BuildingsUseMTId id) {
		this.id = id;
	}
	
}
