package it.sinergis.gsc.model;

// Generated Aug 5, 2016 5:19:16 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BuildingsRenewablePotentiaT generated by hbm2java
 */
@Entity
@Table(name = "BUILDINGS_RENEWABLE_POTENTIA_T")
public class BuildingsRenewablePotentiaT implements java.io.Serializable {
	
	private Buildings buildings;
	private HEnergysource HEnergysource;
	private BuildingsRenewablePotentiaTId id;
	
	public BuildingsRenewablePotentiaT() {
	}
	
	public BuildingsRenewablePotentiaT(BuildingsRenewablePotentiaTId id, Buildings buildings,
	        HEnergysource HEnergysource) {
		this.id = id;
		this.buildings = buildings;
		this.HEnergysource = HEnergysource;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UUID", nullable = false, insertable = false, updatable = false)
	public Buildings getBuildings() {
		return this.buildings;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RENEWABLE_POTEN_RENEWABLE_SOUR", nullable = false, insertable = false, updatable = false)
	public HEnergysource getHEnergysource() {
		return this.HEnergysource;
	}
	
	@EmbeddedId
	@AttributeOverrides({
	        @AttributeOverride(name = "uuid", column = @Column(name = "UUID", nullable = false, length = 70)),
	        @AttributeOverride(name = "renewablePotenRenewableSour", column = @Column(name = "RENEWABLE_POTEN_RENEWABLE_SOUR", nullable = false, length = 80)),
	        @AttributeOverride(name = "renewablePotentialValue", column = @Column(name = "RENEWABLE_POTENTIAL_VALUE", nullable = false, precision = 126, scale = 0)) })
	public BuildingsRenewablePotentiaTId getId() {
		return this.id;
	}
	
	public void setBuildings(Buildings buildings) {
		this.buildings = buildings;
	}
	
	public void setHEnergysource(HEnergysource HEnergysource) {
		this.HEnergysource = HEnergysource;
	}
	
	public void setId(BuildingsRenewablePotentiaTId id) {
		this.id = id;
	}
	
}
