package it.sinergis.gsc.model;

// Generated Aug 5, 2016 5:19:16 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BuildingsRoofMat generated by hbm2java
 */
@Entity
@Table(name = "BUILDINGS_ROOF_MAT")
public class BuildingsRoofMat implements java.io.Serializable {
	
	private Buildings buildings;
	private DMaterial DMaterial;
	private BuildingsRoofMatId id;
	
	public BuildingsRoofMat() {
	}
	
	public BuildingsRoofMat(BuildingsRoofMatId id, Buildings buildings, DMaterial DMaterial) {
		this.id = id;
		this.buildings = buildings;
		this.DMaterial = DMaterial;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UUID", nullable = false, insertable = false, updatable = false)
	public Buildings getBuildings() {
		return this.buildings;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ROOF_MAT", nullable = false, insertable = false, updatable = false)
	public DMaterial getDMaterial() {
		return this.DMaterial;
	}
	
	@EmbeddedId
	@AttributeOverrides({
	        @AttributeOverride(name = "uuid", column = @Column(name = "UUID", nullable = false, length = 70)),
	        @AttributeOverride(name = "roofMat", column = @Column(name = "ROOF_MAT", nullable = false, length = 80)) })
	public BuildingsRoofMatId getId() {
		return this.id;
	}
	
	public void setBuildings(Buildings buildings) {
		this.buildings = buildings;
	}
	
	public void setDMaterial(DMaterial DMaterial) {
		this.DMaterial = DMaterial;
	}
	
	public void setId(BuildingsRoofMatId id) {
		this.id = id;
	}
	
}
