package it.sinergis.gsc.model;

// Generated Aug 5, 2016 5:19:16 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * BuildingsEnergyPerformanceT generated by hbm2java
 */
@Entity
@Table(name = "BUILDINGS_ENERGY_PERFORMANCE_T", uniqueConstraints = @UniqueConstraint(columnNames = { "UUID",
        "CERT_COUNT", "ENERGYPERFORMANCE_PERF_DATE", "ENERGYPERFORMANCE_PERF_METHOD", "ENERGYPERFORMANCE_PERF_UOM",
        "ENERGYPERFORMANCE_PERF_VALUE", "VOLUME_SOURCE", "VOLUME_VALUE", "ENERGYPERFORMANCE_PERF_TYPE" }))
public class BuildingsEnergyPerformanceT implements java.io.Serializable {
	
	private Buildings buildings;
	private BuildingsEnergyPerformanceTId id;
	
	public BuildingsEnergyPerformanceT() {
	}
	
	public BuildingsEnergyPerformanceT(BuildingsEnergyPerformanceTId id) {
		this.id = id;
	}
	
	public BuildingsEnergyPerformanceT(BuildingsEnergyPerformanceTId id, Buildings buildings) {
		this.id = id;
		this.buildings = buildings;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UUID", insertable = false, updatable = false)
	public Buildings getBuildings() {
		return this.buildings;
	}
	
	@EmbeddedId
	@AttributeOverrides({
	        @AttributeOverride(name = "uuid", column = @Column(name = "UUID", length = 70)),
	        @AttributeOverride(name = "certCount", column = @Column(name = "CERT_COUNT", precision = 15, scale = 0)),
	        @AttributeOverride(name = "energyperformancePerfDate", column = @Column(name = "ENERGYPERFORMANCE_PERF_DATE", length = 7)),
	        @AttributeOverride(name = "energyperformancePerfMethod", column = @Column(name = "ENERGYPERFORMANCE_PERF_METHOD", length = 100)),
	        @AttributeOverride(name = "energyperformancePerfUom", column = @Column(name = "ENERGYPERFORMANCE_PERF_UOM", length = 80)),
	        @AttributeOverride(name = "energyperformancePerfValue", column = @Column(name = "ENERGYPERFORMANCE_PERF_VALUE", precision = 126, scale = 0)),
	        @AttributeOverride(name = "volumeSource", column = @Column(name = "VOLUME_SOURCE", length = 80)),
	        @AttributeOverride(name = "volumeValue", column = @Column(name = "VOLUME_VALUE", precision = 126, scale = 0)),
	        @AttributeOverride(name = "energyperformancePerfType", column = @Column(name = "ENERGYPERFORMANCE_PERF_TYPE", length = 80)),
	        @AttributeOverride(name = "energyperformancePerfClass", column = @Column(name = "ENERGYPERFORMANCE_PERF_CLASS", length = 3)) })
	public BuildingsEnergyPerformanceTId getId() {
		return this.id;
	}
	
	public void setBuildings(Buildings buildings) {
		this.buildings = buildings;
	}
	
	public void setId(BuildingsEnergyPerformanceTId id) {
		this.id = id;
	}
	
}
