package it.sinergis.gsc.model;

// Generated Aug 5, 2016 5:19:16 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BuildingsFacadeMat generated by hbm2java
 */
@Entity
@Table(name = "BUILDINGS_FACADE_MAT")
public class BuildingsFacadeMat implements java.io.Serializable {
	
	private Buildings buildings;
	private DMaterial DMaterial;
	private BuildingsFacadeMatId id;
	
	public BuildingsFacadeMat() {
	}
	
	public BuildingsFacadeMat(BuildingsFacadeMatId id, DMaterial DMaterial, Buildings buildings) {
		this.id = id;
		this.DMaterial = DMaterial;
		this.buildings = buildings;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UUID", nullable = false, insertable = false, updatable = false)
	public Buildings getBuildings() {
		return this.buildings;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FACADE_MAT", nullable = false, insertable = false, updatable = false)
	public DMaterial getDMaterial() {
		return this.DMaterial;
	}
	
	@EmbeddedId
	@AttributeOverrides({
	        @AttributeOverride(name = "uuid", column = @Column(name = "UUID", nullable = false, length = 70)),
	        @AttributeOverride(name = "facadeMat", column = @Column(name = "FACADE_MAT", nullable = false, length = 80)) })
	public BuildingsFacadeMatId getId() {
		return this.id;
	}
	
	public void setBuildings(Buildings buildings) {
		this.buildings = buildings;
	}
	
	public void setDMaterial(DMaterial DMaterial) {
		this.DMaterial = DMaterial;
	}
	
	public void setId(BuildingsFacadeMatId id) {
		this.id = id;
	}
	
}
