package it.sinergis.gsc.model;

// Generated Aug 5, 2016 5:19:16 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BuildingsRoofMatId generated by hbm2java
 */
@Embeddable
public class BuildingsRoofMatId implements java.io.Serializable {
	
	private String uuid;
	private String roofMat;
	
	public BuildingsRoofMatId() {
	}
	
	public BuildingsRoofMatId(String uuid, String roofMat) {
		this.uuid = uuid;
		this.roofMat = roofMat;
	}
	
	@Column(name = "UUID", nullable = false, length = 70)
	public String getUuid() {
		return this.uuid;
	}
	
	public void setUuid(String uuid) {
		this.uuid = uuid;
	}
	
	@Column(name = "ROOF_MAT", nullable = false, length = 80)
	public String getRoofMat() {
		return this.roofMat;
	}
	
	public void setRoofMat(String roofMat) {
		this.roofMat = roofMat;
	}
	
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BuildingsRoofMatId))
			return false;
		BuildingsRoofMatId castOther = (BuildingsRoofMatId) other;
		
		return ((this.getUuid() == castOther.getUuid()) || (this.getUuid() != null && castOther.getUuid() != null && this
		        .getUuid().equals(castOther.getUuid())))
		        && ((this.getRoofMat() == castOther.getRoofMat()) || (this.getRoofMat() != null
		                && castOther.getRoofMat() != null && this.getRoofMat().equals(castOther.getRoofMat())));
	}
	
	public int hashCode() {
		int result = 17;
		
		result = 37 * result + (getUuid() == null ? 0 : this.getUuid().hashCode());
		result = 37 * result + (getRoofMat() == null ? 0 : this.getRoofMat().hashCode());
		return result;
	}
	
}
