package it.sinergis.gsc.model;

// Generated Aug 5, 2016 5:19:16 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BuildingsFacadeMatId generated by hbm2java
 */
@Embeddable
public class BuildingsFacadeMatId implements java.io.Serializable {
	
	private String uuid;
	private String facadeMat;
	
	public BuildingsFacadeMatId() {
	}
	
	public BuildingsFacadeMatId(String uuid, String facadeMat) {
		this.uuid = uuid;
		this.facadeMat = facadeMat;
	}
	
	@Column(name = "UUID", nullable = false, length = 70)
	public String getUuid() {
		return this.uuid;
	}
	
	public void setUuid(String uuid) {
		this.uuid = uuid;
	}
	
	@Column(name = "FACADE_MAT", nullable = false, length = 80)
	public String getFacadeMat() {
		return this.facadeMat;
	}
	
	public void setFacadeMat(String facadeMat) {
		this.facadeMat = facadeMat;
	}
	
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BuildingsFacadeMatId))
			return false;
		BuildingsFacadeMatId castOther = (BuildingsFacadeMatId) other;
		
		return ((this.getUuid() == castOther.getUuid()) || (this.getUuid() != null && castOther.getUuid() != null && this
		        .getUuid().equals(castOther.getUuid())))
		        && ((this.getFacadeMat() == castOther.getFacadeMat()) || (this.getFacadeMat() != null
		                && castOther.getFacadeMat() != null && this.getFacadeMat().equals(castOther.getFacadeMat())));
	}
	
	public int hashCode() {
		int result = 17;
		
		result = 37 * result + (getUuid() == null ? 0 : this.getUuid().hashCode());
		result = 37 * result + (getFacadeMat() == null ? 0 : this.getFacadeMat().hashCode());
		return result;
	}
	
}
