package it.sinergis.gsc.model;

// Generated Aug 5, 2016 5:19:16 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BuildingsUseMTId generated by hbm2java
 */
@Embeddable
public class BuildingsUseMTId implements java.io.Serializable {
	
	private String uuid;
	private String useMCurrentuse;
	private long useMPercentage;
	
	public BuildingsUseMTId() {
	}
	
	public BuildingsUseMTId(String uuid, String useMCurrentuse, long useMPercentage) {
		this.uuid = uuid;
		this.useMCurrentuse = useMCurrentuse;
		this.useMPercentage = useMPercentage;
	}
	
	@Column(name = "UUID", nullable = false, length = 70)
	public String getUuid() {
		return this.uuid;
	}
	
	public void setUuid(String uuid) {
		this.uuid = uuid;
	}
	
	@Column(name = "USE_M_CURRENTUSE", nullable = false, length = 80)
	public String getUseMCurrentuse() {
		return this.useMCurrentuse;
	}
	
	public void setUseMCurrentuse(String useMCurrentuse) {
		this.useMCurrentuse = useMCurrentuse;
	}
	
	@Column(name = "USE_M_PERCENTAGE", nullable = false, precision = 15, scale = 0)
	public long getUseMPercentage() {
		return this.useMPercentage;
	}
	
	public void setUseMPercentage(long useMPercentage) {
		this.useMPercentage = useMPercentage;
	}
	
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BuildingsUseMTId))
			return false;
		BuildingsUseMTId castOther = (BuildingsUseMTId) other;
		
		return ((this.getUuid() == castOther.getUuid()) || (this.getUuid() != null && castOther.getUuid() != null && this
		        .getUuid().equals(castOther.getUuid())))
		        && ((this.getUseMCurrentuse() == castOther.getUseMCurrentuse()) || (this.getUseMCurrentuse() != null
		                && castOther.getUseMCurrentuse() != null && this.getUseMCurrentuse().equals(
		                castOther.getUseMCurrentuse()))) && (this.getUseMPercentage() == castOther.getUseMPercentage());
	}
	
	public int hashCode() {
		int result = 17;
		
		result = 37 * result + (getUuid() == null ? 0 : this.getUuid().hashCode());
		result = 37 * result + (getUseMCurrentuse() == null ? 0 : this.getUseMCurrentuse().hashCode());
		result = 37 * result + (int) this.getUseMPercentage();
		return result;
	}
	
}
