package it.sinergis.gsc.model;

// Generated Aug 5, 2016 5:19:16 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BuildingsRenewablePotentiaTId generated by hbm2java
 */
@Embeddable
public class BuildingsRenewablePotentiaTId implements java.io.Serializable {
	
	private String uuid;
	private String renewablePotenRenewableSour;
	private double renewablePotentialValue;
	
	public BuildingsRenewablePotentiaTId() {
	}
	
	public BuildingsRenewablePotentiaTId(String uuid, String renewablePotenRenewableSour, double renewablePotentialValue) {
		this.uuid = uuid;
		this.renewablePotenRenewableSour = renewablePotenRenewableSour;
		this.renewablePotentialValue = renewablePotentialValue;
	}
	
	@Column(name = "UUID", nullable = false, length = 70)
	public String getUuid() {
		return this.uuid;
	}
	
	public void setUuid(String uuid) {
		this.uuid = uuid;
	}
	
	@Column(name = "RENEWABLE_POTEN_RENEWABLE_SOUR", nullable = false, length = 80)
	public String getRenewablePotenRenewableSour() {
		return this.renewablePotenRenewableSour;
	}
	
	public void setRenewablePotenRenewableSour(String renewablePotenRenewableSour) {
		this.renewablePotenRenewableSour = renewablePotenRenewableSour;
	}
	
	@Column(name = "RENEWABLE_POTENTIAL_VALUE", nullable = false, precision = 126, scale = 0)
	public double getRenewablePotentialValue() {
		return this.renewablePotentialValue;
	}
	
	public void setRenewablePotentialValue(double renewablePotentialValue) {
		this.renewablePotentialValue = renewablePotentialValue;
	}
	
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BuildingsRenewablePotentiaTId))
			return false;
		BuildingsRenewablePotentiaTId castOther = (BuildingsRenewablePotentiaTId) other;
		
		return ((this.getUuid() == castOther.getUuid()) || (this.getUuid() != null && castOther.getUuid() != null && this
		        .getUuid().equals(castOther.getUuid())))
		        && ((this.getRenewablePotenRenewableSour() == castOther.getRenewablePotenRenewableSour()) || (this
		                .getRenewablePotenRenewableSour() != null && castOther.getRenewablePotenRenewableSour() != null && this
		                .getRenewablePotenRenewableSour().equals(castOther.getRenewablePotenRenewableSour())))
		        && (this.getRenewablePotentialValue() == castOther.getRenewablePotentialValue());
	}
	
	public int hashCode() {
		int result = 17;
		
		result = 37 * result + (getUuid() == null ? 0 : this.getUuid().hashCode());
		result = 37 * result
		        + (getRenewablePotenRenewableSour() == null ? 0 : this.getRenewablePotenRenewableSour().hashCode());
		result = 37 * result + (int) this.getRenewablePotentialValue();
		return result;
	}
	
}
