package it.sinergis.gsc.model;

// Generated Aug 5, 2016 5:19:16 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BuildingsExtRefTId generated by hbm2java
 */
@Embeddable
public class BuildingsExtRefTId implements java.io.Serializable {
	
	private String uuid;
	private String extRefIdentifier;
	private String extRefInfSysName;
	private String extRefReference;
	
	public BuildingsExtRefTId() {
	}
	
	public BuildingsExtRefTId(String uuid, String extRefIdentifier, String extRefInfSysName, String extRefReference) {
		this.uuid = uuid;
		this.extRefIdentifier = extRefIdentifier;
		this.extRefInfSysName = extRefInfSysName;
		this.extRefReference = extRefReference;
	}
	
	@Column(name = "UUID", nullable = false, length = 70)
	public String getUuid() {
		return this.uuid;
	}
	
	public void setUuid(String uuid) {
		this.uuid = uuid;
	}
	
	@Column(name = "EXT_REF_IDENTIFIER", nullable = false, length = 100)
	public String getExtRefIdentifier() {
		return this.extRefIdentifier;
	}
	
	public void setExtRefIdentifier(String extRefIdentifier) {
		this.extRefIdentifier = extRefIdentifier;
	}
	
	@Column(name = "EXT_REF_INF_SYS_NAME", nullable = false, length = 100)
	public String getExtRefInfSysName() {
		return this.extRefInfSysName;
	}
	
	public void setExtRefInfSysName(String extRefInfSysName) {
		this.extRefInfSysName = extRefInfSysName;
	}
	
	@Column(name = "EXT_REF_REFERENCE", nullable = false, length = 40)
	public String getExtRefReference() {
		return this.extRefReference;
	}
	
	public void setExtRefReference(String extRefReference) {
		this.extRefReference = extRefReference;
	}
	
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BuildingsExtRefTId))
			return false;
		BuildingsExtRefTId castOther = (BuildingsExtRefTId) other;
		
		return ((this.getUuid() == castOther.getUuid()) || (this.getUuid() != null && castOther.getUuid() != null && this
		        .getUuid().equals(castOther.getUuid())))
		        && ((this.getExtRefIdentifier() == castOther.getExtRefIdentifier()) || (this.getExtRefIdentifier() != null
		                && castOther.getExtRefIdentifier() != null && this.getExtRefIdentifier().equals(
		                castOther.getExtRefIdentifier())))
		        && ((this.getExtRefInfSysName() == castOther.getExtRefInfSysName()) || (this.getExtRefInfSysName() != null
		                && castOther.getExtRefInfSysName() != null && this.getExtRefInfSysName().equals(
		                castOther.getExtRefInfSysName())))
		        && ((this.getExtRefReference() == castOther.getExtRefReference()) || (this.getExtRefReference() != null
		                && castOther.getExtRefReference() != null && this.getExtRefReference().equals(
		                castOther.getExtRefReference())));
	}
	
	public int hashCode() {
		int result = 17;
		
		result = 37 * result + (getUuid() == null ? 0 : this.getUuid().hashCode());
		result = 37 * result + (getExtRefIdentifier() == null ? 0 : this.getExtRefIdentifier().hashCode());
		result = 37 * result + (getExtRefInfSysName() == null ? 0 : this.getExtRefInfSysName().hashCode());
		result = 37 * result + (getExtRefReference() == null ? 0 : this.getExtRefReference().hashCode());
		return result;
	}
	
}
