package it.sinergis.gsc.model;

// Generated Aug 5, 2016 5:19:16 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * BuildingsElevationT generated by hbm2java
 */
@Entity
@Table(name = "BUILDINGS_ELEVATION_T", uniqueConstraints = @UniqueConstraint(columnNames = { "UUID",
        "ELEVATION_ELEV_VAL", "ELEVATION_ELEVATIONREFERENCE" }))
public class BuildingsElevationT implements java.io.Serializable {
	
	private Buildings buildings;
	private DElevationreference DElevationreference;
	private BuildingsElevationTId id;
	
	public BuildingsElevationT() {
	}
	
	public BuildingsElevationT(BuildingsElevationTId id) {
		this.id = id;
	}
	
	public BuildingsElevationT(BuildingsElevationTId id, DElevationreference DElevationreference, Buildings buildings) {
		this.id = id;
		this.DElevationreference = DElevationreference;
		this.buildings = buildings;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UUID", insertable = false, updatable = false)
	public Buildings getBuildings() {
		return this.buildings;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ELEVATION_ELEVATIONREFERENCE", insertable = false, updatable = false)
	public DElevationreference getDElevationreference() {
		return this.DElevationreference;
	}
	
	@EmbeddedId
	@AttributeOverrides({
	        @AttributeOverride(name = "uuid", column = @Column(name = "UUID", length = 70)),
	        @AttributeOverride(name = "elevationElevVal", column = @Column(name = "ELEVATION_ELEV_VAL", precision = 15, scale = 0)),
	        @AttributeOverride(name = "elevationElevationreference", column = @Column(name = "ELEVATION_ELEVATIONREFERENCE", length = 80)) })
	public BuildingsElevationTId getId() {
		return this.id;
	}
	
	public void setBuildings(Buildings buildings) {
		this.buildings = buildings;
	}
	
	public void setDElevationreference(DElevationreference DElevationreference) {
		this.DElevationreference = DElevationreference;
	}
	
	public void setId(BuildingsElevationTId id) {
		this.id = id;
	}
	
}
