package it.sinergis.gsc.model;

// Generated Aug 5, 2016 5:19:16 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BuildingsExtRefT generated by hbm2java
 */
@Entity
@Table(name = "BUILDINGS_EXT_REF_T")
public class BuildingsExtRefT implements java.io.Serializable {
	
	private Buildings buildings;
	private BuildingsExtRefTId id;
	
	public BuildingsExtRefT() {
	}
	
	public BuildingsExtRefT(BuildingsExtRefTId id, Buildings buildings) {
		this.id = id;
		this.buildings = buildings;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UUID", nullable = false, insertable = false, updatable = false)
	public Buildings getBuildings() {
		return this.buildings;
	}
	
	@EmbeddedId
	@AttributeOverrides({
	        @AttributeOverride(name = "uuid", column = @Column(name = "UUID", nullable = false, length = 70)),
	        @AttributeOverride(name = "extRefIdentifier", column = @Column(name = "EXT_REF_IDENTIFIER", nullable = false, length = 100)),
	        @AttributeOverride(name = "extRefInfSysName", column = @Column(name = "EXT_REF_INF_SYS_NAME", nullable = false, length = 100)),
	        @AttributeOverride(name = "extRefReference", column = @Column(name = "EXT_REF_REFERENCE", nullable = false, length = 40)) })
	public BuildingsExtRefTId getId() {
		return this.id;
	}
	
	public void setBuildings(Buildings buildings) {
		this.buildings = buildings;
	}
	
	public void setId(BuildingsExtRefTId id) {
		this.id = id;
	}
	
}
