package it.sinergis.gsc.model;

// Generated Aug 5, 2016 5:19:16 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Conversion generated by hbm2java
 */
@Entity
@Table(name = "CONVERSION")
public class Conversion implements java.io.Serializable {
	
	private HEnergysource HEnergysource;
	private HLocation HLocation;
	private HUom HUomByInput;
	private HUom HUomByOutput;
	private String uuid;
	private double value;
	private Date year;
	
	public Conversion() {
	}
	
	public Conversion(String uuid, HUom HUomByOutput, HLocation HLocation, HEnergysource HEnergysource,
	        HUom HUomByInput, double value, Date year) {
		this.uuid = uuid;
		this.HUomByOutput = HUomByOutput;
		this.HLocation = HLocation;
		this.HEnergysource = HEnergysource;
		this.HUomByInput = HUomByInput;
		this.value = value;
		this.year = year;
	}
	
	public Conversion(String uuid, HUom HUomByOutput, HUom HUomByInput, double value) {
		this.uuid = uuid;
		this.HUomByOutput = HUomByOutput;
		this.HUomByInput = HUomByInput;
		this.value = value;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FUEL")
	public HEnergysource getHEnergysource() {
		return this.HEnergysource;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LOCATION")
	public HLocation getHLocation() {
		return this.HLocation;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "INPUT", nullable = false)
	public HUom getHUomByInput() {
		return this.HUomByInput;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "OUTPUT", nullable = false)
	public HUom getHUomByOutput() {
		return this.HUomByOutput;
	}
	
	@Id
	@Column(name = "UUID", unique = true, nullable = false, length = 70)
	public String getUuid() {
		return this.uuid;
	}
	
	@Column(name = "VALUE", nullable = false, precision = 126, scale = 0)
	public double getValue() {
		return this.value;
	}
	
	@Temporal(TemporalType.DATE)
	@Column(name = "YEAR", length = 7)
	public Date getYear() {
		return this.year;
	}
	
	public void setHEnergysource(HEnergysource HEnergysource) {
		this.HEnergysource = HEnergysource;
	}
	
	public void setHLocation(HLocation HLocation) {
		this.HLocation = HLocation;
	}
	
	public void setHUomByInput(HUom HUomByInput) {
		this.HUomByInput = HUomByInput;
	}
	
	public void setHUomByOutput(HUom HUomByOutput) {
		this.HUomByOutput = HUomByOutput;
	}
	
	public void setUuid(String uuid) {
		this.uuid = uuid;
	}
	
	public void setValue(double value) {
		this.value = value;
	}
	
	public void setYear(Date year) {
		this.year = year;
	}
	
}
