package it.sinergis.gsc.model;

// Generated Aug 5, 2016 5:19:16 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DElevationreference generated by hbm2java
 */
@Entity
@Table(name = "D_ELEVATIONREFERENCE")
public class DElevationreference implements java.io.Serializable {
	
	private String alphacode;
	private Set<BuildingsElevationT> buildingsElevationTs = new HashSet<BuildingsElevationT>(0);
	private Set<Buildings> buildingsesForElevRef = new HashSet<Buildings>(0);
	private Set<Buildings> buildingsesForHeightHeightLow = new HashSet<Buildings>(0);
	private Set<Buildings> buildingsesForHeightHeightRef = new HashSet<Buildings>(0);
	private String code;
	private String definition;
	private Set<InstallationElevationT> installationElevationTs = new HashSet<InstallationElevationT>(0);
	private Set<Installation> installationsForElevRef = new HashSet<Installation>(0);
	private Set<Installation> installationsForHeightHeightLow = new HashSet<Installation>(0);
	private Set<Installation> installationsForHeightHeightRef = new HashSet<Installation>(0);
	private String name;
	
	public DElevationreference() {
	}
	
	public DElevationreference(String code) {
		this.code = code;
	}
	
	public DElevationreference(String code, String name, String definition, String alphacode,
	        Set<Buildings> buildingsesForHeightHeightRef, Set<Buildings> buildingsesForHeightHeightLow,
	        Set<Buildings> buildingsesForElevRef, Set<InstallationElevationT> installationElevationTs,
	        Set<Installation> installationsForHeightHeightRef, Set<BuildingsElevationT> buildingsElevationTs,
	        Set<Installation> installationsForElevRef, Set<Installation> installationsForHeightHeightLow) {
		this.code = code;
		this.name = name;
		this.definition = definition;
		this.alphacode = alphacode;
		this.buildingsesForHeightHeightRef = buildingsesForHeightHeightRef;
		this.buildingsesForHeightHeightLow = buildingsesForHeightHeightLow;
		this.buildingsesForElevRef = buildingsesForElevRef;
		this.installationElevationTs = installationElevationTs;
		this.installationsForHeightHeightRef = installationsForHeightHeightRef;
		this.buildingsElevationTs = buildingsElevationTs;
		this.installationsForElevRef = installationsForElevRef;
		this.installationsForHeightHeightLow = installationsForHeightHeightLow;
	}
	
	@Column(name = "ALPHACODE", length = 80)
	public String getAlphacode() {
		return this.alphacode;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "DElevationreference")
	public Set<BuildingsElevationT> getBuildingsElevationTs() {
		return this.buildingsElevationTs;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "DElevationreferenceByElevRef")
	public Set<Buildings> getBuildingsesForElevRef() {
		return this.buildingsesForElevRef;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "DElevationreferenceByHeightHeightLow")
	public Set<Buildings> getBuildingsesForHeightHeightLow() {
		return this.buildingsesForHeightHeightLow;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "DElevationreferenceByHeightHeightRef")
	public Set<Buildings> getBuildingsesForHeightHeightRef() {
		return this.buildingsesForHeightHeightRef;
	}
	
	@Id
	@Column(name = "CODE", unique = true, nullable = false, length = 80)
	public String getCode() {
		return this.code;
	}
	
	@Column(name = "DEFINITION", length = 1200)
	public String getDefinition() {
		return this.definition;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "DElevationreference")
	public Set<InstallationElevationT> getInstallationElevationTs() {
		return this.installationElevationTs;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "DElevationreferenceByElevRef")
	public Set<Installation> getInstallationsForElevRef() {
		return this.installationsForElevRef;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "DElevationreferenceByHeightHeightLow")
	public Set<Installation> getInstallationsForHeightHeightLow() {
		return this.installationsForHeightHeightLow;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "DElevationreferenceByHeightHeightRef")
	public Set<Installation> getInstallationsForHeightHeightRef() {
		return this.installationsForHeightHeightRef;
	}
	
	@Column(name = "NAME", length = 160)
	public String getName() {
		return this.name;
	}
	
	public void setAlphacode(String alphacode) {
		this.alphacode = alphacode;
	}
	
	public void setBuildingsElevationTs(Set<BuildingsElevationT> buildingsElevationTs) {
		this.buildingsElevationTs = buildingsElevationTs;
	}
	
	public void setBuildingsesForElevRef(Set<Buildings> buildingsesForElevRef) {
		this.buildingsesForElevRef = buildingsesForElevRef;
	}
	
	public void setBuildingsesForHeightHeightLow(Set<Buildings> buildingsesForHeightHeightLow) {
		this.buildingsesForHeightHeightLow = buildingsesForHeightHeightLow;
	}
	
	public void setBuildingsesForHeightHeightRef(Set<Buildings> buildingsesForHeightHeightRef) {
		this.buildingsesForHeightHeightRef = buildingsesForHeightHeightRef;
	}
	
	public void setCode(String code) {
		this.code = code;
	}
	
	public void setDefinition(String definition) {
		this.definition = definition;
	}
	
	public void setInstallationElevationTs(Set<InstallationElevationT> installationElevationTs) {
		this.installationElevationTs = installationElevationTs;
	}
	
	public void setInstallationsForElevRef(Set<Installation> installationsForElevRef) {
		this.installationsForElevRef = installationsForElevRef;
	}
	
	public void setInstallationsForHeightHeightLow(Set<Installation> installationsForHeightHeightLow) {
		this.installationsForHeightHeightLow = installationsForHeightHeightLow;
	}
	
	public void setInstallationsForHeightHeightRef(Set<Installation> installationsForHeightHeightRef) {
		this.installationsForHeightHeightRef = installationsForHeightHeightRef;
	}
	
	public void setName(String name) {
		this.name = name;
	}
	
}
