package it.sinergis.gsc.model;

// Generated Aug 5, 2016 5:19:16 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DEnergyuse generated by hbm2java
 */
@Entity
@Table(name = "D_ENERGYUSE")
public class DEnergyuse implements java.io.Serializable {
	
	private String alphacode;
	private Set<BuildingsEnergyamountT> buildingsEnergyamountTs = new HashSet<BuildingsEnergyamountT>(0);
	private String code;
	private String definition;
	private String name;
	private Set<ThermalzoneEnergyamountT> thermalzoneEnergyamountTs = new HashSet<ThermalzoneEnergyamountT>(0);
	
	public DEnergyuse() {
	}
	
	public DEnergyuse(String code) {
		this.code = code;
	}
	
	public DEnergyuse(String code, String name, String definition, String alphacode,
	        Set<ThermalzoneEnergyamountT> thermalzoneEnergyamountTs, Set<BuildingsEnergyamountT> buildingsEnergyamountTs) {
		this.code = code;
		this.name = name;
		this.definition = definition;
		this.alphacode = alphacode;
		this.thermalzoneEnergyamountTs = thermalzoneEnergyamountTs;
		this.buildingsEnergyamountTs = buildingsEnergyamountTs;
	}
	
	@Column(name = "ALPHACODE", length = 80)
	public String getAlphacode() {
		return this.alphacode;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "DEnergyuse")
	public Set<BuildingsEnergyamountT> getBuildingsEnergyamountTs() {
		return this.buildingsEnergyamountTs;
	}
	
	@Id
	@Column(name = "CODE", unique = true, nullable = false, length = 80)
	public String getCode() {
		return this.code;
	}
	
	@Column(name = "DEFINITION", length = 1200)
	public String getDefinition() {
		return this.definition;
	}
	
	@Column(name = "NAME", length = 160)
	public String getName() {
		return this.name;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "DEnergyuse")
	public Set<ThermalzoneEnergyamountT> getThermalzoneEnergyamountTs() {
		return this.thermalzoneEnergyamountTs;
	}
	
	public void setAlphacode(String alphacode) {
		this.alphacode = alphacode;
	}
	
	public void setBuildingsEnergyamountTs(Set<BuildingsEnergyamountT> buildingsEnergyamountTs) {
		this.buildingsEnergyamountTs = buildingsEnergyamountTs;
	}
	
	public void setCode(String code) {
		this.code = code;
	}
	
	public void setDefinition(String definition) {
		this.definition = definition;
	}
	
	public void setName(String name) {
		this.name = name;
	}
	
	public void setThermalzoneEnergyamountTs(Set<ThermalzoneEnergyamountT> thermalzoneEnergyamountTs) {
		this.thermalzoneEnergyamountTs = thermalzoneEnergyamountTs;
	}
	
}
