package it.sinergis.gsc.model;

// Generated Aug 5, 2016 5:19:16 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DHeatingsystem generated by hbm2java
 */
@Entity
@Table(name = "D_HEATINGSYSTEM")
public class DHeatingsystem implements java.io.Serializable {
	
	private String alphacode;
	private String code;
	private String definition;
	private String name;
	private Set<ThermalzoneHeatingsystem> thermalzoneHeatingsystems = new HashSet<ThermalzoneHeatingsystem>(0);
	
	public DHeatingsystem() {
	}
	
	public DHeatingsystem(String code) {
		this.code = code;
	}
	
	public DHeatingsystem(String code, String name, String definition, String alphacode,
	        Set<ThermalzoneHeatingsystem> thermalzoneHeatingsystems) {
		this.code = code;
		this.name = name;
		this.definition = definition;
		this.alphacode = alphacode;
		this.thermalzoneHeatingsystems = thermalzoneHeatingsystems;
	}
	
	@Column(name = "ALPHACODE", length = 80)
	public String getAlphacode() {
		return this.alphacode;
	}
	
	@Id
	@Column(name = "CODE", unique = true, nullable = false, length = 80)
	public String getCode() {
		return this.code;
	}
	
	@Column(name = "DEFINITION", length = 1200)
	public String getDefinition() {
		return this.definition;
	}
	
	@Column(name = "NAME", length = 160)
	public String getName() {
		return this.name;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "DHeatingsystem")
	public Set<ThermalzoneHeatingsystem> getThermalzoneHeatingsystems() {
		return this.thermalzoneHeatingsystems;
	}
	
	public void setAlphacode(String alphacode) {
		this.alphacode = alphacode;
	}
	
	public void setCode(String code) {
		this.code = code;
	}
	
	public void setDefinition(String definition) {
		this.definition = definition;
	}
	
	public void setName(String name) {
		this.name = name;
	}
	
	public void setThermalzoneHeatingsystems(Set<ThermalzoneHeatingsystem> thermalzoneHeatingsystems) {
		this.thermalzoneHeatingsystems = thermalzoneHeatingsystems;
	}
	
}
