package it.sinergis.gsc.model;

// Generated Aug 5, 2016 5:19:16 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DMaterial generated by hbm2java
 */
@Entity
@Table(name = "D_MATERIAL")
public class DMaterial implements java.io.Serializable {
	
	private String alphacode;
	private Set<BuildingsFacadeMat> buildingsFacadeMats = new HashSet<BuildingsFacadeMat>(0);
	private Set<BuildingsRoofMat> buildingsRoofMats = new HashSet<BuildingsRoofMat>(0);
	private Set<BuildingsStructureMat> buildingsStructureMats = new HashSet<BuildingsStructureMat>(0);
	private String code;
	private String definition;
	private String name;
	
	public DMaterial() {
	}
	
	public DMaterial(String code) {
		this.code = code;
	}
	
	public DMaterial(String code, String name, String definition, String alphacode,
	        Set<BuildingsRoofMat> buildingsRoofMats, Set<BuildingsStructureMat> buildingsStructureMats,
	        Set<BuildingsFacadeMat> buildingsFacadeMats) {
		this.code = code;
		this.name = name;
		this.definition = definition;
		this.alphacode = alphacode;
		this.buildingsRoofMats = buildingsRoofMats;
		this.buildingsStructureMats = buildingsStructureMats;
		this.buildingsFacadeMats = buildingsFacadeMats;
	}
	
	@Column(name = "ALPHACODE", length = 80)
	public String getAlphacode() {
		return this.alphacode;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "DMaterial")
	public Set<BuildingsFacadeMat> getBuildingsFacadeMats() {
		return this.buildingsFacadeMats;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "DMaterial")
	public Set<BuildingsRoofMat> getBuildingsRoofMats() {
		return this.buildingsRoofMats;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "DMaterial")
	public Set<BuildingsStructureMat> getBuildingsStructureMats() {
		return this.buildingsStructureMats;
	}
	
	@Id
	@Column(name = "CODE", unique = true, nullable = false, length = 80)
	public String getCode() {
		return this.code;
	}
	
	@Column(name = "DEFINITION", length = 1200)
	public String getDefinition() {
		return this.definition;
	}
	
	@Column(name = "NAME", length = 160)
	public String getName() {
		return this.name;
	}
	
	public void setAlphacode(String alphacode) {
		this.alphacode = alphacode;
	}
	
	public void setBuildingsFacadeMats(Set<BuildingsFacadeMat> buildingsFacadeMats) {
		this.buildingsFacadeMats = buildingsFacadeMats;
	}
	
	public void setBuildingsRoofMats(Set<BuildingsRoofMat> buildingsRoofMats) {
		this.buildingsRoofMats = buildingsRoofMats;
	}
	
	public void setBuildingsStructureMats(Set<BuildingsStructureMat> buildingsStructureMats) {
		this.buildingsStructureMats = buildingsStructureMats;
	}
	
	public void setCode(String code) {
		this.code = code;
	}
	
	public void setDefinition(String definition) {
		this.definition = definition;
	}
	
	public void setName(String name) {
		this.name = name;
	}
	
}
