package it.sinergis.gsc.model;

// Generated Aug 5, 2016 5:19:16 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DPerfClass generated by hbm2java
 */
@Entity
@Table(name = "D_PERF_CLASS")
public class DPerfClass implements java.io.Serializable {
	
	private String alphacode;
	private String code;
	private String definition;
	private String name;
	private Set<Thermalzone> thermalzones = new HashSet<Thermalzone>(0);
	
	public DPerfClass() {
	}
	
	public DPerfClass(String code) {
		this.code = code;
	}
	
	public DPerfClass(String code, String name, String definition, String alphacode, Set<Thermalzone> thermalzones) {
		this.code = code;
		this.name = name;
		this.definition = definition;
		this.alphacode = alphacode;
		this.thermalzones = thermalzones;
	}
	
	@Column(name = "ALPHACODE", length = 80)
	public String getAlphacode() {
		return this.alphacode;
	}
	
	@Id
	@Column(name = "CODE", unique = true, nullable = false, length = 80)
	public String getCode() {
		return this.code;
	}
	
	@Column(name = "DEFINITION", length = 1200)
	public String getDefinition() {
		return this.definition;
	}
	
	@Column(name = "NAME", length = 160)
	public String getName() {
		return this.name;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "DPerfClass")
	public Set<Thermalzone> getThermalzones() {
		return this.thermalzones;
	}
	
	public void setAlphacode(String alphacode) {
		this.alphacode = alphacode;
	}
	
	public void setCode(String code) {
		this.code = code;
	}
	
	public void setDefinition(String definition) {
		this.definition = definition;
	}
	
	public void setName(String name) {
		this.name = name;
	}
	
	public void setThermalzones(Set<Thermalzone> thermalzones) {
		this.thermalzones = thermalzones;
	}
	
}
