package it.sinergis.gsc.model;

// Generated Aug 5, 2016 5:19:16 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DTypeValue generated by hbm2java
 */
@Entity
@Table(name = "D_TYPE_VALUE")
public class DTypeValue implements java.io.Serializable {
	
	private String alphacode;
	private String code;
	private String definition;
	private Set<Installation> installations = new HashSet<Installation>(0);
	private String name;
	
	public DTypeValue() {
	}
	
	public DTypeValue(String code) {
		this.code = code;
	}
	
	public DTypeValue(String code, String name, String definition, String alphacode, Set<Installation> installations) {
		this.code = code;
		this.name = name;
		this.definition = definition;
		this.alphacode = alphacode;
		this.installations = installations;
	}
	
	@Column(name = "ALPHACODE", length = 80)
	public String getAlphacode() {
		return this.alphacode;
	}
	
	@Id
	@Column(name = "CODE", unique = true, nullable = false, length = 80)
	public String getCode() {
		return this.code;
	}
	
	@Column(name = "DEFINITION", length = 1200)
	public String getDefinition() {
		return this.definition;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "DTypeValue")
	public Set<Installation> getInstallations() {
		return this.installations;
	}
	
	@Column(name = "NAME", length = 160)
	public String getName() {
		return this.name;
	}
	
	public void setAlphacode(String alphacode) {
		this.alphacode = alphacode;
	}
	
	public void setCode(String code) {
		this.code = code;
	}
	
	public void setDefinition(String definition) {
		this.definition = definition;
	}
	
	public void setInstallations(Set<Installation> installations) {
		this.installations = installations;
	}
	
	public void setName(String name) {
		this.name = name;
	}
	
}
