package it.sinergis.gsc.model;

// Generated Aug 5, 2016 5:19:16 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * HEnergysource generated by hbm2java
 */
@Entity
@Table(name = "H_ENERGYSOURCE")
public class HEnergysource implements java.io.Serializable {
	
	private String alphacode;
	private Set<BuildingsEnergyamountT> buildingsEnergyamountTs = new HashSet<BuildingsEnergyamountT>(0);
	private Set<BuildingsRenewablePotentiaT> buildingsRenewablePotentiaTs = new HashSet<BuildingsRenewablePotentiaT>(0);
	private String code;
	private Set<Conversion> conversions = new HashSet<Conversion>(0);
	private String definition;
	private String name;
	private Set<ThermalzoneEnergyamountT> thermalzoneEnergyamountTs = new HashSet<ThermalzoneEnergyamountT>(0);
	private Set<ThermalzoneHeatingsource> thermalzoneHeatingsources = new HashSet<ThermalzoneHeatingsource>(0);
	
	public HEnergysource() {
	}
	
	public HEnergysource(String code) {
		this.code = code;
	}
	
	public HEnergysource(String code, String name, String definition, String alphacode,
	        Set<ThermalzoneHeatingsource> thermalzoneHeatingsources, Set<Conversion> conversions,
	        Set<BuildingsRenewablePotentiaT> buildingsRenewablePotentiaTs,
	        Set<ThermalzoneEnergyamountT> thermalzoneEnergyamountTs, Set<BuildingsEnergyamountT> buildingsEnergyamountTs) {
		this.code = code;
		this.name = name;
		this.definition = definition;
		this.alphacode = alphacode;
		this.thermalzoneHeatingsources = thermalzoneHeatingsources;
		this.conversions = conversions;
		this.buildingsRenewablePotentiaTs = buildingsRenewablePotentiaTs;
		this.thermalzoneEnergyamountTs = thermalzoneEnergyamountTs;
		this.buildingsEnergyamountTs = buildingsEnergyamountTs;
	}
	
	@Column(name = "ALPHACODE", length = 80)
	public String getAlphacode() {
		return this.alphacode;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "HEnergysource")
	public Set<BuildingsEnergyamountT> getBuildingsEnergyamountTs() {
		return this.buildingsEnergyamountTs;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "HEnergysource")
	public Set<BuildingsRenewablePotentiaT> getBuildingsRenewablePotentiaTs() {
		return this.buildingsRenewablePotentiaTs;
	}
	
	@Id
	@Column(name = "CODE", unique = true, nullable = false, length = 80)
	public String getCode() {
		return this.code;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "HEnergysource")
	public Set<Conversion> getConversions() {
		return this.conversions;
	}
	
	@Column(name = "DEFINITION", length = 1200)
	public String getDefinition() {
		return this.definition;
	}
	
	@Column(name = "NAME", length = 850)
	public String getName() {
		return this.name;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "HEnergysource")
	public Set<ThermalzoneEnergyamountT> getThermalzoneEnergyamountTs() {
		return this.thermalzoneEnergyamountTs;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "HEnergysource")
	public Set<ThermalzoneHeatingsource> getThermalzoneHeatingsources() {
		return this.thermalzoneHeatingsources;
	}
	
	public void setAlphacode(String alphacode) {
		this.alphacode = alphacode;
	}
	
	public void setBuildingsEnergyamountTs(Set<BuildingsEnergyamountT> buildingsEnergyamountTs) {
		this.buildingsEnergyamountTs = buildingsEnergyamountTs;
	}
	
	public void setBuildingsRenewablePotentiaTs(Set<BuildingsRenewablePotentiaT> buildingsRenewablePotentiaTs) {
		this.buildingsRenewablePotentiaTs = buildingsRenewablePotentiaTs;
	}
	
	public void setCode(String code) {
		this.code = code;
	}
	
	public void setConversions(Set<Conversion> conversions) {
		this.conversions = conversions;
	}
	
	public void setDefinition(String definition) {
		this.definition = definition;
	}
	
	public void setName(String name) {
		this.name = name;
	}
	
	public void setThermalzoneEnergyamountTs(Set<ThermalzoneEnergyamountT> thermalzoneEnergyamountTs) {
		this.thermalzoneEnergyamountTs = thermalzoneEnergyamountTs;
	}
	
	public void setThermalzoneHeatingsources(Set<ThermalzoneHeatingsource> thermalzoneHeatingsources) {
		this.thermalzoneHeatingsources = thermalzoneHeatingsources;
	}
	
}
