package it.sinergis.gsc.model;

// Generated Aug 5, 2016 5:19:16 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * HLocation generated by hbm2java
 */
@Entity
@Table(name = "H_LOCATION")
public class HLocation implements java.io.Serializable {
	
	private String alphacode;
	private String code;
	private Set<Conversion> conversions = new HashSet<Conversion>(0);
	private String definition;
	private String name;
	
	public HLocation() {
	}
	
	public HLocation(String code) {
		this.code = code;
	}
	
	public HLocation(String code, String name, String definition, String alphacode, Set<Conversion> conversions) {
		this.code = code;
		this.name = name;
		this.definition = definition;
		this.alphacode = alphacode;
		this.conversions = conversions;
	}
	
	@Column(name = "ALPHACODE", length = 80)
	public String getAlphacode() {
		return this.alphacode;
	}
	
	@Id
	@Column(name = "CODE", unique = true, nullable = false, length = 80)
	public String getCode() {
		return this.code;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "HLocation")
	public Set<Conversion> getConversions() {
		return this.conversions;
	}
	
	@Column(name = "DEFINITION", length = 1200)
	public String getDefinition() {
		return this.definition;
	}
	
	@Column(name = "NAME", length = 850)
	public String getName() {
		return this.name;
	}
	
	public void setAlphacode(String alphacode) {
		this.alphacode = alphacode;
	}
	
	public void setCode(String code) {
		this.code = code;
	}
	
	public void setConversions(Set<Conversion> conversions) {
		this.conversions = conversions;
	}
	
	public void setDefinition(String definition) {
		this.definition = definition;
	}
	
	public void setName(String name) {
		this.name = name;
	}
	
}
