package it.sinergis.gsc.model;

// Generated Aug 5, 2016 5:19:16 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * InstallationElevationT generated by hbm2java
 */
@Entity
@Table(name = "INSTALLATION_ELEVATION_T", uniqueConstraints = @UniqueConstraint(columnNames = { "UUID",
        "ELEVATION_ELEV_VAL", "ELEVATION_ELEVATIONREFERENCE" }))
public class InstallationElevationT implements java.io.Serializable {
	
	private DElevationreference DElevationreference;
	private InstallationElevationTId id;
	private Installation installation;
	
	public InstallationElevationT() {
	}
	
	public InstallationElevationT(InstallationElevationTId id) {
		this.id = id;
	}
	
	public InstallationElevationT(InstallationElevationTId id, DElevationreference DElevationreference,
	        Installation installation) {
		this.id = id;
		this.DElevationreference = DElevationreference;
		this.installation = installation;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ELEVATION_ELEVATIONREFERENCE", insertable = false, updatable = false)
	public DElevationreference getDElevationreference() {
		return this.DElevationreference;
	}
	
	@EmbeddedId
	@AttributeOverrides({
	        @AttributeOverride(name = "uuid", column = @Column(name = "UUID", length = 70)),
	        @AttributeOverride(name = "elevationElevVal", column = @Column(name = "ELEVATION_ELEV_VAL", precision = 15, scale = 0)),
	        @AttributeOverride(name = "elevationElevationreference", column = @Column(name = "ELEVATION_ELEVATIONREFERENCE", length = 80)) })
	public InstallationElevationTId getId() {
		return this.id;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UUID", insertable = false, updatable = false)
	public Installation getInstallation() {
		return this.installation;
	}
	
	public void setDElevationreference(DElevationreference DElevationreference) {
		this.DElevationreference = DElevationreference;
	}
	
	public void setId(InstallationElevationTId id) {
		this.id = id;
	}
	
	public void setInstallation(Installation installation) {
		this.installation = installation;
	}
	
}
