package it.sinergis.gsc.model;

// Generated Aug 5, 2016 5:19:16 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * InstallationExtRefT generated by hbm2java
 */
@Entity
@Table(name = "INSTALLATION_EXT_REF_T")
public class InstallationExtRefT implements java.io.Serializable {
	
	private InstallationExtRefTId id;
	private Installation installation;
	
	public InstallationExtRefT() {
	}
	
	public InstallationExtRefT(InstallationExtRefTId id, Installation installation) {
		this.id = id;
		this.installation = installation;
	}
	
	@EmbeddedId
	@AttributeOverrides({
	        @AttributeOverride(name = "uuid", column = @Column(name = "UUID", nullable = false, length = 70)),
	        @AttributeOverride(name = "extRefIdentifier", column = @Column(name = "EXT_REF_IDENTIFIER", nullable = false, length = 100)),
	        @AttributeOverride(name = "extRefInfSysName", column = @Column(name = "EXT_REF_INF_SYS_NAME", nullable = false, length = 100)),
	        @AttributeOverride(name = "extRefReference", column = @Column(name = "EXT_REF_REFERENCE", nullable = false, length = 40)) })
	public InstallationExtRefTId getId() {
		return this.id;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UUID", nullable = false, insertable = false, updatable = false)
	public Installation getInstallation() {
		return this.installation;
	}
	
	public void setId(InstallationExtRefTId id) {
		this.id = id;
	}
	
	public void setInstallation(Installation installation) {
		this.installation = installation;
	}
	
}
