package it.sinergis.gsc.model;

// Generated Aug 5, 2016 5:19:16 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * InstallationElevationTId generated by hbm2java
 */
@Embeddable
public class InstallationElevationTId implements java.io.Serializable {
	
	private String uuid;
	private Long elevationElevVal;
	private String elevationElevationreference;
	
	public InstallationElevationTId() {
	}
	
	public InstallationElevationTId(String uuid, Long elevationElevVal, String elevationElevationreference) {
		this.uuid = uuid;
		this.elevationElevVal = elevationElevVal;
		this.elevationElevationreference = elevationElevationreference;
	}
	
	@Column(name = "UUID", length = 70)
	public String getUuid() {
		return this.uuid;
	}
	
	public void setUuid(String uuid) {
		this.uuid = uuid;
	}
	
	@Column(name = "ELEVATION_ELEV_VAL", precision = 15, scale = 0)
	public Long getElevationElevVal() {
		return this.elevationElevVal;
	}
	
	public void setElevationElevVal(Long elevationElevVal) {
		this.elevationElevVal = elevationElevVal;
	}
	
	@Column(name = "ELEVATION_ELEVATIONREFERENCE", length = 80)
	public String getElevationElevationreference() {
		return this.elevationElevationreference;
	}
	
	public void setElevationElevationreference(String elevationElevationreference) {
		this.elevationElevationreference = elevationElevationreference;
	}
	
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof InstallationElevationTId))
			return false;
		InstallationElevationTId castOther = (InstallationElevationTId) other;
		
		return ((this.getUuid() == castOther.getUuid()) || (this.getUuid() != null && castOther.getUuid() != null && this
		        .getUuid().equals(castOther.getUuid())))
		        && ((this.getElevationElevVal() == castOther.getElevationElevVal()) || (this.getElevationElevVal() != null
		                && castOther.getElevationElevVal() != null && this.getElevationElevVal().equals(
		                castOther.getElevationElevVal())))
		        && ((this.getElevationElevationreference() == castOther.getElevationElevationreference()) || (this
		                .getElevationElevationreference() != null && castOther.getElevationElevationreference() != null && this
		                .getElevationElevationreference().equals(castOther.getElevationElevationreference())));
	}
	
	public int hashCode() {
		int result = 17;
		
		result = 37 * result + (getUuid() == null ? 0 : this.getUuid().hashCode());
		result = 37 * result + (getElevationElevVal() == null ? 0 : this.getElevationElevVal().hashCode());
		result = 37 * result
		        + (getElevationElevationreference() == null ? 0 : this.getElevationElevationreference().hashCode());
		return result;
	}
	
}
