package it.sinergis.gsc.model;

// Generated Aug 5, 2016 5:19:16 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ThermalzoneHeatingsourceId generated by hbm2java
 */
@Embeddable
public class ThermalzoneHeatingsourceId implements java.io.Serializable {
	
	private String uuid;
	private String heatingsource;
	
	public ThermalzoneHeatingsourceId() {
	}
	
	public ThermalzoneHeatingsourceId(String uuid, String heatingsource) {
		this.uuid = uuid;
		this.heatingsource = heatingsource;
	}
	
	@Column(name = "UUID", nullable = false, length = 70)
	public String getUuid() {
		return this.uuid;
	}
	
	public void setUuid(String uuid) {
		this.uuid = uuid;
	}
	
	@Column(name = "HEATINGSOURCE", nullable = false, length = 80)
	public String getHeatingsource() {
		return this.heatingsource;
	}
	
	public void setHeatingsource(String heatingsource) {
		this.heatingsource = heatingsource;
	}
	
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ThermalzoneHeatingsourceId))
			return false;
		ThermalzoneHeatingsourceId castOther = (ThermalzoneHeatingsourceId) other;
		
		return ((this.getUuid() == castOther.getUuid()) || (this.getUuid() != null && castOther.getUuid() != null && this
		        .getUuid().equals(castOther.getUuid())))
		        && ((this.getHeatingsource() == castOther.getHeatingsource()) || (this.getHeatingsource() != null
		                && castOther.getHeatingsource() != null && this.getHeatingsource().equals(
		                castOther.getHeatingsource())));
	}
	
	public int hashCode() {
		int result = 17;
		
		result = 37 * result + (getUuid() == null ? 0 : this.getUuid().hashCode());
		result = 37 * result + (getHeatingsource() == null ? 0 : this.getHeatingsource().hashCode());
		return result;
	}
	
}
