package it.sinergis.gsc.model;

// Generated Aug 5, 2016 5:19:16 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Thermalzone generated by hbm2java
 */
@Entity
@Table(name = "THERMALZONE")
public class Thermalzone implements java.io.Serializable {
	
	private Buildings buildings;
	private DOccupancytype DOccupancytype;
	private DPerfClass DPerfClass;
	private Date energyperformancePerfDate;
	private String energyperformancePerfMethod;
	private Long energyperformancePerfValue;
	private HUom HUom;
	private Set<Installation> installations = new HashSet<Installation>(0);
	private Long occupantsOccValue;
	private Set<ThermalzoneEnergyamountT> thermalzoneEnergyamountTs = new HashSet<ThermalzoneEnergyamountT>(0);
	private Set<ThermalzoneHeatingsource> thermalzoneHeatingsources = new HashSet<ThermalzoneHeatingsource>(0);
	private Set<ThermalzoneHeatingsystem> thermalzoneHeatingsystems = new HashSet<ThermalzoneHeatingsystem>(0);
	private Set<ThermalzoneOfficialareaT> thermalzoneOfficialareaTs = new HashSet<ThermalzoneOfficialareaT>(0);
	private String uuid;
	private String volumeSource;
	private Double volumeValue;
	
	public Thermalzone() {
	}
	
	public Thermalzone(String uuid, Buildings buildings) {
		this.uuid = uuid;
		this.buildings = buildings;
	}
	
	public Thermalzone(String uuid, Buildings buildings, DPerfClass DPerfClass, DOccupancytype DOccupancytype,
	        HUom HUom, Date energyperformancePerfDate, String energyperformancePerfMethod,
	        Long energyperformancePerfValue, Long occupantsOccValue, String volumeSource, Double volumeValue,
	        Set<ThermalzoneHeatingsource> thermalzoneHeatingsources,
	        Set<ThermalzoneHeatingsystem> thermalzoneHeatingsystems,
	        Set<ThermalzoneOfficialareaT> thermalzoneOfficialareaTs,
	        Set<ThermalzoneEnergyamountT> thermalzoneEnergyamountTs, Set<Installation> installations) {
		this.uuid = uuid;
		this.buildings = buildings;
		this.DPerfClass = DPerfClass;
		this.DOccupancytype = DOccupancytype;
		this.HUom = HUom;
		this.energyperformancePerfDate = energyperformancePerfDate;
		this.energyperformancePerfMethod = energyperformancePerfMethod;
		this.energyperformancePerfValue = energyperformancePerfValue;
		this.occupantsOccValue = occupantsOccValue;
		this.volumeSource = volumeSource;
		this.volumeValue = volumeValue;
		this.thermalzoneHeatingsources = thermalzoneHeatingsources;
		this.thermalzoneHeatingsystems = thermalzoneHeatingsystems;
		this.thermalzoneOfficialareaTs = thermalzoneOfficialareaTs;
		this.thermalzoneEnergyamountTs = thermalzoneEnergyamountTs;
		this.installations = installations;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UUID_TZ2BDG", nullable = false)
	public Buildings getBuildings() {
		return this.buildings;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "OCCUPANTS_OCC_TYPE")
	public DOccupancytype getDOccupancytype() {
		return this.DOccupancytype;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ENERGYPERFORMANCE_PERF_CLASS")
	public DPerfClass getDPerfClass() {
		return this.DPerfClass;
	}
	
	@Temporal(TemporalType.DATE)
	@Column(name = "ENERGYPERFORMANCE_PERF_DATE", length = 7)
	public Date getEnergyperformancePerfDate() {
		return this.energyperformancePerfDate;
	}
	
	@Column(name = "ENERGYPERFORMANCE_PERF_METHOD", length = 100)
	public String getEnergyperformancePerfMethod() {
		return this.energyperformancePerfMethod;
	}
	
	@Column(name = "ENERGYPERFORMANCE_PERF_VALUE", precision = 15, scale = 0)
	public Long getEnergyperformancePerfValue() {
		return this.energyperformancePerfValue;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ENERGYPERFORMANCE_PERF_UOM")
	public HUom getHUom() {
		return this.HUom;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "thermalzone")
	public Set<Installation> getInstallations() {
		return this.installations;
	}
	
	@Column(name = "OCCUPANTS_OCC_VALUE", precision = 15, scale = 0)
	public Long getOccupantsOccValue() {
		return this.occupantsOccValue;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "thermalzone")
	public Set<ThermalzoneEnergyamountT> getThermalzoneEnergyamountTs() {
		return this.thermalzoneEnergyamountTs;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "thermalzone")
	public Set<ThermalzoneHeatingsource> getThermalzoneHeatingsources() {
		return this.thermalzoneHeatingsources;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "thermalzone")
	public Set<ThermalzoneHeatingsystem> getThermalzoneHeatingsystems() {
		return this.thermalzoneHeatingsystems;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "thermalzone")
	public Set<ThermalzoneOfficialareaT> getThermalzoneOfficialareaTs() {
		return this.thermalzoneOfficialareaTs;
	}
	
	@Id
	@Column(name = "UUID", unique = true, nullable = false, length = 70)
	public String getUuid() {
		return this.uuid;
	}
	
	@Column(name = "VOLUME_SOURCE", length = 40)
	public String getVolumeSource() {
		return this.volumeSource;
	}
	
	@Column(name = "VOLUME_VALUE", precision = 126, scale = 0)
	public Double getVolumeValue() {
		return this.volumeValue;
	}
	
	public void setBuildings(Buildings buildings) {
		this.buildings = buildings;
	}
	
	public void setDOccupancytype(DOccupancytype DOccupancytype) {
		this.DOccupancytype = DOccupancytype;
	}
	
	public void setDPerfClass(DPerfClass DPerfClass) {
		this.DPerfClass = DPerfClass;
	}
	
	public void setEnergyperformancePerfDate(Date energyperformancePerfDate) {
		this.energyperformancePerfDate = energyperformancePerfDate;
	}
	
	public void setEnergyperformancePerfMethod(String energyperformancePerfMethod) {
		this.energyperformancePerfMethod = energyperformancePerfMethod;
	}
	
	public void setEnergyperformancePerfValue(Long energyperformancePerfValue) {
		this.energyperformancePerfValue = energyperformancePerfValue;
	}
	
	public void setHUom(HUom HUom) {
		this.HUom = HUom;
	}
	
	public void setInstallations(Set<Installation> installations) {
		this.installations = installations;
	}
	
	public void setOccupantsOccValue(Long occupantsOccValue) {
		this.occupantsOccValue = occupantsOccValue;
	}
	
	public void setThermalzoneEnergyamountTs(Set<ThermalzoneEnergyamountT> thermalzoneEnergyamountTs) {
		this.thermalzoneEnergyamountTs = thermalzoneEnergyamountTs;
	}
	
	public void setThermalzoneHeatingsources(Set<ThermalzoneHeatingsource> thermalzoneHeatingsources) {
		this.thermalzoneHeatingsources = thermalzoneHeatingsources;
	}
	
	public void setThermalzoneHeatingsystems(Set<ThermalzoneHeatingsystem> thermalzoneHeatingsystems) {
		this.thermalzoneHeatingsystems = thermalzoneHeatingsystems;
	}
	
	public void setThermalzoneOfficialareaTs(Set<ThermalzoneOfficialareaT> thermalzoneOfficialareaTs) {
		this.thermalzoneOfficialareaTs = thermalzoneOfficialareaTs;
	}
	
	public void setUuid(String uuid) {
		this.uuid = uuid;
	}
	
	public void setVolumeSource(String volumeSource) {
		this.volumeSource = volumeSource;
	}
	
	public void setVolumeValue(Double volumeValue) {
		this.volumeValue = volumeValue;
	}
	
}
