package it.sinergis.gsc.model;

// Generated Aug 5, 2016 5:19:16 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ThermalzoneOfficialareaTId generated by hbm2java
 */
@Embeddable
public class ThermalzoneOfficialareaTId implements java.io.Serializable {
	
	private String uuid;
	private String officialareaAreaRef;
	private double officialareaValue;
	
	public ThermalzoneOfficialareaTId() {
	}
	
	public ThermalzoneOfficialareaTId(String uuid, String officialareaAreaRef, double officialareaValue) {
		this.uuid = uuid;
		this.officialareaAreaRef = officialareaAreaRef;
		this.officialareaValue = officialareaValue;
	}
	
	@Column(name = "UUID", nullable = false, length = 70)
	public String getUuid() {
		return this.uuid;
	}
	
	public void setUuid(String uuid) {
		this.uuid = uuid;
	}
	
	@Column(name = "OFFICIALAREA_AREA_REF", nullable = false, length = 80)
	public String getOfficialareaAreaRef() {
		return this.officialareaAreaRef;
	}
	
	public void setOfficialareaAreaRef(String officialareaAreaRef) {
		this.officialareaAreaRef = officialareaAreaRef;
	}
	
	@Column(name = "OFFICIALAREA_VALUE", nullable = false, precision = 126, scale = 0)
	public double getOfficialareaValue() {
		return this.officialareaValue;
	}
	
	public void setOfficialareaValue(double officialareaValue) {
		this.officialareaValue = officialareaValue;
	}
	
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ThermalzoneOfficialareaTId))
			return false;
		ThermalzoneOfficialareaTId castOther = (ThermalzoneOfficialareaTId) other;
		
		return ((this.getUuid() == castOther.getUuid()) || (this.getUuid() != null && castOther.getUuid() != null && this
		        .getUuid().equals(castOther.getUuid())))
		        && ((this.getOfficialareaAreaRef() == castOther.getOfficialareaAreaRef()) || (this
		                .getOfficialareaAreaRef() != null && castOther.getOfficialareaAreaRef() != null && this
		                .getOfficialareaAreaRef().equals(castOther.getOfficialareaAreaRef())))
		        && (this.getOfficialareaValue() == castOther.getOfficialareaValue());
	}
	
	public int hashCode() {
		int result = 17;
		
		result = 37 * result + (getUuid() == null ? 0 : this.getUuid().hashCode());
		result = 37 * result + (getOfficialareaAreaRef() == null ? 0 : this.getOfficialareaAreaRef().hashCode());
		result = 37 * result + (int) this.getOfficialareaValue();
		return result;
	}
	
}
