package it.sinergis.gsc.model;

// Generated Aug 5, 2016 5:19:16 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ThermalzoneOfficialareaT generated by hbm2java
 */
@Entity
@Table(name = "THERMALZONE_OFFICIALAREA_T")
public class ThermalzoneOfficialareaT implements java.io.Serializable {
	
	private DClge DClge;
	private ThermalzoneOfficialareaTId id;
	private Thermalzone thermalzone;
	
	public ThermalzoneOfficialareaT() {
	}
	
	public ThermalzoneOfficialareaT(ThermalzoneOfficialareaTId id, Thermalzone thermalzone, DClge DClge) {
		this.id = id;
		this.thermalzone = thermalzone;
		this.DClge = DClge;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "OFFICIALAREA_AREA_REF", nullable = false, insertable = false, updatable = false)
	public DClge getDClge() {
		return this.DClge;
	}
	
	@EmbeddedId
	@AttributeOverrides({
	        @AttributeOverride(name = "uuid", column = @Column(name = "UUID", nullable = false, length = 70)),
	        @AttributeOverride(name = "officialareaAreaRef", column = @Column(name = "OFFICIALAREA_AREA_REF", nullable = false, length = 80)),
	        @AttributeOverride(name = "officialareaValue", column = @Column(name = "OFFICIALAREA_VALUE", nullable = false, precision = 126, scale = 0)) })
	public ThermalzoneOfficialareaTId getId() {
		return this.id;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UUID", nullable = false, insertable = false, updatable = false)
	public Thermalzone getThermalzone() {
		return this.thermalzone;
	}
	
	public void setDClge(DClge DClge) {
		this.DClge = DClge;
	}
	
	public void setId(ThermalzoneOfficialareaTId id) {
		this.id = id;
	}
	
	public void setThermalzone(Thermalzone thermalzone) {
		this.thermalzone = thermalzone;
	}
	
}
