package it.sinergis.gsc.model;

// Generated Aug 5, 2016 5:19:16 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ThermalzoneHeatingsystemId generated by hbm2java
 */
@Embeddable
public class ThermalzoneHeatingsystemId implements java.io.Serializable {
	
	private String uuid;
	private String heatingsystem;
	
	public ThermalzoneHeatingsystemId() {
	}
	
	public ThermalzoneHeatingsystemId(String uuid, String heatingsystem) {
		this.uuid = uuid;
		this.heatingsystem = heatingsystem;
	}
	
	@Column(name = "UUID", nullable = false, length = 70)
	public String getUuid() {
		return this.uuid;
	}
	
	public void setUuid(String uuid) {
		this.uuid = uuid;
	}
	
	@Column(name = "HEATINGSYSTEM", nullable = false, length = 80)
	public String getHeatingsystem() {
		return this.heatingsystem;
	}
	
	public void setHeatingsystem(String heatingsystem) {
		this.heatingsystem = heatingsystem;
	}
	
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ThermalzoneHeatingsystemId))
			return false;
		ThermalzoneHeatingsystemId castOther = (ThermalzoneHeatingsystemId) other;
		
		return ((this.getUuid() == castOther.getUuid()) || (this.getUuid() != null && castOther.getUuid() != null && this
		        .getUuid().equals(castOther.getUuid())))
		        && ((this.getHeatingsystem() == castOther.getHeatingsystem()) || (this.getHeatingsystem() != null
		                && castOther.getHeatingsystem() != null && this.getHeatingsystem().equals(
		                castOther.getHeatingsystem())));
	}
	
	public int hashCode() {
		int result = 17;
		
		result = 37 * result + (getUuid() == null ? 0 : this.getUuid().hashCode());
		result = 37 * result + (getHeatingsystem() == null ? 0 : this.getHeatingsystem().hashCode());
		return result;
	}
	
}
