//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.03 at 12:13:34 PM CET 
//


package it.sinergis.routingpreferences.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for routingPreferenceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="routingPreferenceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="UserID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MaxWalkDistance" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="WalkingSpeed" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="MaxBikeDistance" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="BikingSpeed" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "routingPreferenceType", propOrder = {
    "userID",
    "maxWalkDistance",
    "walkingSpeed",
    "maxBikeDistance",
    "bikingSpeed"
})
public class RoutingPreferenceType {

    @XmlElement(name = "UserID", required = true)
    protected String userID;
    @XmlElement(name = "MaxWalkDistance")
    protected int maxWalkDistance;
    @XmlElement(name = "WalkingSpeed")
    protected int walkingSpeed;
    @XmlElement(name = "MaxBikeDistance")
    protected int maxBikeDistance;
    @XmlElement(name = "BikingSpeed")
    protected int bikingSpeed;

    /**
     * Gets the value of the userID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserID() {
        return userID;
    }

    /**
     * Sets the value of the userID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserID(String value) {
        this.userID = value;
    }

    /**
     * Gets the value of the maxWalkDistance property.
     * 
     */
    public int getMaxWalkDistance() {
        return maxWalkDistance;
    }

    /**
     * Sets the value of the maxWalkDistance property.
     * 
     */
    public void setMaxWalkDistance(int value) {
        this.maxWalkDistance = value;
    }

    /**
     * Gets the value of the walkingSpeed property.
     * 
     */
    public int getWalkingSpeed() {
        return walkingSpeed;
    }

    /**
     * Sets the value of the walkingSpeed property.
     * 
     */
    public void setWalkingSpeed(int value) {
        this.walkingSpeed = value;
    }

    /**
     * Gets the value of the maxBikeDistance property.
     * 
     */
    public int getMaxBikeDistance() {
        return maxBikeDistance;
    }

    /**
     * Sets the value of the maxBikeDistance property.
     * 
     */
    public void setMaxBikeDistance(int value) {
        this.maxBikeDistance = value;
    }

    /**
     * Gets the value of the bikingSpeed property.
     * 
     */
    public int getBikingSpeed() {
        return bikingSpeed;
    }

    /**
     * Sets the value of the bikingSpeed property.
     * 
     */
    public void setBikingSpeed(int value) {
        this.bikingSpeed = value;
    }

}
