//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.03 at 11:24:58 AM CET 
//


package it.sinergis.routingpreferences.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="routingPreference" type="{}routingPreferenceType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "routingPreference"
})
@XmlRootElement(name = "routingPreferenceInsertRequest")
public class RoutingPreferenceInsertRequest {

    @XmlElement(required = true)
    protected RoutingPreferenceType routingPreference;

    /**
     * Gets the value of the routingPreference property.
     * 
     * @return
     *     possible object is
     *     {@link RoutingPreferenceType }
     *     
     */
    public RoutingPreferenceType getRoutingPreference() {
        return routingPreference;
    }

    /**
     * Sets the value of the routingPreference property.
     * 
     * @param value
     *     allowed object is
     *     {@link RoutingPreferenceType }
     *     
     */
    public void setRoutingPreference(RoutingPreferenceType value) {
        this.routingPreference = value;
    }

}
